import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export interface ExpenseClaim {
  id: string;
  claim_number: string;
  user_id: string;
  start_date: string;
  end_date: string;
  city_category: string;
  working_days: number;
  da_amount: number;
  distance_travelled: number;
  fuel_amount: number;
  hotel_nights: number;
  hotel_amount: number;
  other_amount: number;
  other_description: string | null;
  total_amount: number;
  status: string;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  rejection_reason: string | null;
  created_at: string;
  updated_at: string;
  user_name?: string;
}

export interface CreateExpenseData {
  start_date: string;
  end_date: string;
  city_category: string;
  working_days: number;
  da_amount: number;
  distance_travelled: number;
  fuel_amount: number;
  hotel_nights: number;
  hotel_amount: number;
  other_amount: number;
  other_description?: string;
  total_amount: number;
}

export function useExpenseClaims(statusFilter?: string) {
  return useQuery({
    queryKey: ['expense-claims', statusFilter],
    queryFn: async () => {
      let query = supabase
        .from('expense_claims')
        .select('*')
        .order('created_at', { ascending: false });

      if (statusFilter && statusFilter !== 'all') {
        query = query.eq('status', statusFilter);
      }

      const { data, error } = await query;
      if (error) throw error;

      // Fetch user names for each claim
      const claimsWithNames = await Promise.all(
        (data || []).map(async (claim) => {
          const { data: profile } = await supabase
            .from('profiles')
            .select('name')
            .eq('id', claim.user_id)
            .maybeSingle();
          return {
            ...claim,
            user_name: profile?.name || 'Unknown User',
          };
        })
      );

      return claimsWithNames as ExpenseClaim[];
    },
  });
}

export function useCreateExpenseClaim() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateExpenseData) => {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('Not authenticated');

      const insertData = {
        ...data,
        user_id: user.user.id,
        status: 'pending',
        submitted_at: new Date().toISOString(),
        claim_number: '', // Auto-generated by trigger
      };

      const { data: result, error } = await supabase
        .from('expense_claims')
        .insert(insertData)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expense-claims'] });
      toast.success('Expense claim submitted for approval');
    },
    onError: (error) => {
      toast.error('Failed to submit expense claim: ' + error.message);
    },
  });
}

export function useUpdateExpenseClaim() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<ExpenseClaim> & { id: string }) => {
      const { data: result, error } = await supabase
        .from('expense_claims')
        .update(data)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expense-claims'] });
      toast.success('Expense claim updated');
    },
    onError: (error) => {
      toast.error('Failed to update expense claim: ' + error.message);
    },
  });
}

export function useApproveExpenseClaim() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('Not authenticated');

      const { data: result, error } = await supabase
        .from('expense_claims')
        .update({
          status: 'approved',
          approved_by: user.user.id,
          approved_at: new Date().toISOString(),
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expense-claims'] });
      toast.success('Expense claim approved');
    },
    onError: (error) => {
      toast.error('Failed to approve claim: ' + error.message);
    },
  });
}

export function useRejectExpenseClaim() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, reason }: { id: string; reason: string }) => {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('Not authenticated');

      const { data: result, error } = await supabase
        .from('expense_claims')
        .update({
          status: 'rejected',
          approved_by: user.user.id,
          approved_at: new Date().toISOString(),
          rejection_reason: reason,
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expense-claims'] });
      toast.success('Expense claim rejected');
    },
    onError: (error) => {
      toast.error('Failed to reject claim: ' + error.message);
    },
  });
}
