import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface Vendor {
  id: string;
  vendor_code: string;
  firm_name: string;
  contact_person: string;
  contact_number: string;
  alternate_number?: string | null;
  email: string;
  gstin?: string | null;
  pan?: string | null;
  business_type: string;
  credit_limit: number;
  credit_days: number;
  outstanding_amount: number;
  address: string;
  country?: string | null;
  state: string;
  city: string;
  zone?: string | null;
  since_date?: string | null;
  assigned_manager_id?: string | null;
  assigned_manager?: { id: string; name: string; email: string } | null;
  status: string;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export function useVendors() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['vendors'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('vendors')
        .select(`
          *,
          assigned_manager:profiles!assigned_manager_id (id, name, email)
        `)
        .order('firm_name');
      if (error) throw error;
      return data as unknown as Vendor[];
    },
    enabled: !!user,
  });
}

export function useVendor(id: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['vendors', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('vendors')
        .select(`
          *,
          assigned_manager:profiles!assigned_manager_id (id, name, email)
        `)
        .eq('id', id)
        .maybeSingle();
      if (error) throw error;
      return data as unknown as Vendor | null;
    },
    enabled: !!user && !!id,
  });
}

export function useCreateVendor() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: Omit<Vendor, 'id' | 'vendor_code' | 'created_at' | 'updated_at' | 'assigned_manager'>) => {
      const { data: result, error } = await supabase
        .from('vendors')
        .insert({
          ...data,
          vendor_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['vendors'] });
      toast.success('Vendor created successfully');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to create vendor');
    },
  });
}

export function useUpdateVendor() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: { id: string; [key: string]: any }) => {
      const { data: result, error } = await supabase
        .from('vendors')
        .update(data)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['vendors'] });
      toast.success('Vendor updated successfully');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to update vendor');
    },
  });
}

export function useDeleteVendor() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('vendors').delete().eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['vendors'] });
      toast.success('Vendor deleted successfully');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to delete vendor');
    },
  });
}
