import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface Warehouse {
  id: string;
  name: string;
  code: string;
  location_type: 'central' | 'depot';
  country: string | null;
  state: string;
  city: string;
  territory: string | null;
  latitude: number | null;
  longitude: number | null;
  address: string | null;
  contact_person: string | null;
  contact_number: string | null;
  contact_person_id: string | null;
  alt_contact_person: string | null;
  alt_contact_number: string | null;
  images: string[] | null;
  capacity: string | null;
  status: 'active' | 'inactive';
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateWarehouseData {
  name: string;
  code?: string;
  location_type: 'central' | 'depot';
  country?: string;
  state: string;
  city: string;
  territory?: string;
  latitude?: number;
  longitude?: number;
  address?: string;
  contact_person?: string;
  contact_number?: string;
  contact_person_id?: string;
  alt_contact_person?: string;
  alt_contact_number?: string;
  images?: string[];
  capacity?: string;
  status?: 'active' | 'inactive';
}

export const useWarehouses = () => {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['warehouses'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('warehouses')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data as Warehouse[];
    },
    enabled: !!user,
  });
};

export const useWarehouse = (id: string | undefined) => {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['warehouse', id],
    queryFn: async () => {
      if (!id) throw new Error('Warehouse ID required');
      
      const { data, error } = await supabase
        .from('warehouses')
        .select('*')
        .eq('id', id)
        .single();
      
      if (error) throw error;
      return data as Warehouse;
    },
    enabled: !!user && !!id,
  });
};

export const useCreateWarehouse = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();
  
  return useMutation({
    mutationFn: async (warehouse: CreateWarehouseData) => {
      // Pass empty code - it will be auto-generated by trigger
      const { code, ...warehouseData } = warehouse;
      const { data, error } = await supabase
        .from('warehouses')
        .insert([{ ...warehouseData, code: '', created_by: user?.id }])
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['warehouses'] });
      toast.success('Warehouse created successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to create warehouse: ${error.message}`);
    },
  });
};

export const useUpdateWarehouse = () => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, ...updates }: Partial<Warehouse> & { id: string }) => {
      const { data, error } = await supabase
        .from('warehouses')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['warehouses'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse'] });
      toast.success('Warehouse updated successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to update warehouse: ${error.message}`);
    },
  });
};

export const useDeleteWarehouse = () => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('warehouses')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['warehouses'] });
      toast.success('Warehouse deleted successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete warehouse: ${error.message}`);
    },
  });
};
